### ISSUE TITLE
UITabBarItem问题

### ISSUE THREAD

**Issue by boluomeng** [nixzhu/Bible-Assistant#1]
UITabBarItem的选中图片在IOS7+无效

**Comment by cisolarix** [comment]
是图中最下面的那几个按钮的选择状态无效？
![如图](http://blog-img-bed.qiniudn.com/bible.assistant.png)

**Comment by boluomeng** [comment]
// 设置 UITabBarController 的 UITabBarItem 选中状态的图片（普通状态在 Storyboard 里已经设置）
  UITabBarController *tabBarController = (UITabBarController *)self.window.rootViewController;
  UITabBarItem *tabBarItem1 = [tabBarController.tabBar.items objectAtIndex:0];
  UITabBarItem *tabBarItem2 = [tabBarController.tabBar.items objectAtIndex:1];
  //UITabBarItem *tabBarItem3 = [tabBarController.tabBar.items objectAtIndex:2]; // 这个是搜索，使用系统原生的搜索
  UITabBarItem *tabBarItem4 = [tabBarController.tabBar.items objectAtIndex:3];
  UITabBarItem *tabBarItem5 = [tabBarController.tabBar.items objectAtIndex:4];

  tabBarItem1.selectedImage = [UIImage imageNamed:@"s_bible_selected"];
  tabBarItem2.selectedImage = [UIImage imageNamed:@"leaf_selected"];
  //tabBarItem3.selectedImage = [UIImage imageNamed:@"search-selected.png"];
  tabBarItem4.selectedImage = [UIImage imageNamed:@"audio_list_selected"];
  tabBarItem5.selectedImage = [UIImage imageNamed:@"settings_selected”];
这代码在ios7执行是没有效果的，ios6可以显示效果。请问下有什么好的解决办法没?

原始邮件
发件人:cisolarixnotifications@github.com
收件人:nixzhu/Bible-AssistantBible-Assistant@noreply.github.com
抄送:boluomengliyunlong8859@gmail.com
发送时间:2014年5月19日(周一) 14:09
主题:Re: [Bible-Assistant] UITabBarItem问题 (#1)

是图中下面的那几个按钮的选择状态无效？

**Comment by cisolarix** [comment]
请看我在二楼的附图，是有效果的。没有重现你所提到的情景。可否提供截图看看？

**Comment by boluomeng** [comment]
这两张图片一张是iOS6，一张是iOS7.tabbar的选中效果是不一样的。

原始邮件
发件人:cisolarixnotifications@github.com
收件人:nixzhu/Bible-AssistantBible-Assistant@noreply.github.com
抄送:boluomengliyunlong8859@gmail.com
发送时间:2014年5月19日(周一) 14:41
主题:Re: [Bible-Assistant] UITabBarItem问题 (#1)

请看我在二楼的附图，是有效果的。没有重现你所提到的情景。可否提供截图看看？

**Comment by cisolarix** [comment]
没看到图片……

**Comment by boluomeng** [comment]
![qq20140519-1](https://cloud.githubusercontent.com/assets/2267743/3011004/0348695e-df23-11e3-93be-c56ecc63e234.png)
![qq20140519-2](https://cloud.githubusercontent.com/assets/2267743/3011005/06d43f58-df23-11e3-8cc6-f02e243362ee.png)

**Comment by cisolarix** [comment]
参见这个[链接](http://esoftmobile.com/2014/01/14/build-ios6-ios7-apps/)

> iOS6中 Tab 选中后，图片默认会加上高光效果，title默认为白色，而iOS7中默认为选中后图片和文字默认都变为 TabBar 的 tintColor 颜色，所以这里的处理方法是准备两套 tabBarItem 的图标，默认状态和选中状态，iOS7直接调用initWithTitle: image: selectedImage:方法初始化 tabBarItem，iOS6在初始化后，再通过 setFinishedSelectedImage: withFinishedUnselectedImage:方法设置默认状态和选中状态下的图标，我通常会给 UITabBarItem 增加一个分类，新增一个统一的初始化方法：
> 
> ```
> @implementation UITabBarItem (Universal)
> + (instancetype)itemWithTitle:(NSString *)title image:(UIImage *)image selectedImage:(UIImage *)selectedImage
> {
>     UITabBarItem *tabBarItem = nil;
>     if (IOS7_OR_LATER) {
>         tabBarItem = [[UITabBarItem alloc] initWithTitle:title image:image selectedImage:selectedImage];
>     } else {
>         tabBarItem = [[UITabBarItem alloc] initWithTitle:title image:nil tag:0];
>         [tabBarItem setFinishedSelectedImage:selectedImage withFinishedUnselectedImage:image];
>     }
>     return tabBarItem;
> }
> @end
> ```

我这儿只有 iOS 7 的模拟器，没有 iOS 6 的 版本，你用上面链接中的代码测试一下，如何？
